Vagrant.configure('2') do |config|
  config.vm.box = 'minimal/xenial64'
  config.vm.network 'forwarded_port', guest: 80, host: 8080, auto_correct: true
  config.vm.provision 'shell' do |s|
    s.inline = 'apt-get update; apt-get -y install nginx; service nginx start'
  end
end
